
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

        <script type="text/javascript">
            $(document).ready(function () {
                $(".tipoFisico").hide();
                $(".tipoJuridico").hide();
                $('input[type=radio][name=tipoPessoa]').change(function () {
                    if (this.value === 'fisica') {
                        $(".tipoFisico").show();
                        $(".tipoJuridico").hide();
                    }
                    else if (this.value === 'juridica') {
                        $(".tipoFisico").hide();
                        $(".tipoJuridico").show();
                    }
                });
            });
        </script>


        <title>Cadastro</title>

        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="css/font-awesome.min.css">
        <link rel="stylesheet" href="css/animate.css">
        <link href="css/animate.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet" />

        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

        <style>
            .tipoFisico{
                color:black;
            }
            .tipoJuridico{
                color:black;
            }

            .form-group .form-control{
                border-color: #999;
            }
        </style>

    </head>
    <body>
    <header id="header">
        <nav class="navbar navbar-default navbar-static-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        <a href="index.html"><h1>Acessibility</h1></a>
                    </div>
                </div>
                <div class="navbar-collapse collapse">
                    <div class="menu">
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation"><a href="index.html">Home</a></li>
                            <li role="presentation"><a href="sobre.html">Sobre</a></li>
                            <li role="presentation"><a href="tipos.html">Tipos</a></li>
                            <li role="presentation"><a href="login.html">Login</a></li>
                            <li role="presentation"><a href="cadastro.phtml" class="active">Cadastre-se</a></li>
                        </ul>
                    </div>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
    </header><!--/header-->


    <section class="contact-page">
        <div class="container">

            <div class="text-center">
                <h2>Cadastre-se</h2>
            </div>

            <div class="row contact-wrap">
                <div class="status alert alert-success" style="display: none"></div>

                <form id="main-contact-form" class="contact-form" name="contact-form" method="POST" action="../tcc/controlador/conexao.php">

                    <div class="col-sm-5 col-sm-offset-1">

                        <!-- NOME -->
                        <div class="form-group">
                            <label>Nome *</label>
                            <input type="text" name="nome" class="form-control" required="required">
                        </div>

                        <!-- EMAIL -->
                        <div class="form-group">
                            <label>Email *</label>
                            <input type="email" name="email" class="form-control" required="required">
                        </div>

                        <!-- SENHA -->
                        <div class="form-group">
                            <label>Senha *</label>
                            <input name="senha" type="password" class="form-control">
                        </div>

                        <!-- CONFIRME A SENHA -->
                        <div class="form-group">
                            <label>Confirme a senha *</label>
                            <input name="senha" type="password" class="form-control">
                        </div>

                        <!--  usuario-->
                        <div class="form-group">
                            <label>Você é um usuário: </label>
                        </div>

                        <!-- tipos -->
                        <div class="form-group">
                            <label> Físico  <input id="campoFisica" type="radio" name="tipoPessoa" value="fisica"> </label>
                            <label> Jurídico<input id="campoJuridica" type="radio" name="tipoPessoa" value="juridica"> </label>
                        </div>

                        <!-- CPF -->
                        <div class="form-group">
                            <label class="tipoFisico">Informe seu CPF *</label>
                            <br>
                            <input class="tipoFisico" type="text" name="cpf">
                        </div>

                        <!-- EQUIPAMENTO -->
                        <div class="form-group>">
                        <label class="tipoFisico">Qual equipamento você utiliza? *</label>
                        <br>
                            <select class="tipoFisico" name="especificacao" size="1">
                              <option>Selecione</option>
                             <option>Andador</option>
                             <option>Bengala</option>
                             <option>Cadeira de rodas manual</option>
                             <option>Cadeira motorizada</option>
                             <option>Muleta Auxiliar</option>
                            </select>
                        </div>

                        <!-- NOME EMPRESA -->
                        <div class="form-group">
                            <label class="tipoJuridico">Nome da empresa *</label>
                        <br>
                            <input class="tipoJuridico" type="text" name="razao_social">
                        </div>

                        <!-- CPNJ -->
                        <div class="form-group">
                            <label class="tipoJuridico">Informe o CPNJ *</label>
                            <br>
                            <input class="tipoJuridico" type="text" name="cnpj" >
                        </div>

                        <div class="form-group">
                            <button type="submit" name="submit" class="btn btn-primary btn-lg" required="required">Cadastrar</button>
                        </div>

                    </div> <!-- /class="form-control-->
                </form>
        </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#contact-page-->

    <footer>

    </footer>

    <div class="sub-footer">
        <div class="container">
            <div class="social-icon">
                <div class="col-md-4">
                    <ul class="social-network">
                        <li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
                    </ul>
                </div> <!-- /class col-md-4 -->
            </div> <!-- /class ssocial-icon -->
        </div>	<!-- /class container -->
    </div> <!-- /class sub-footer -->

    </body>
    </html>